spring:
  profiles:
    active: test

default:
  sender: email@gmail.com
  recipient: email@gmail.com

jwt:
  secret: HereComesTheSecretToSignThePassword
  expiration: 86400000

aws:
  access_key_id:
  secret_access_key:

s3:
  bucket:
  region: