spring:
  profiles:
    active: test
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

default:
  sender: email@gmail.com
  recipient: email@gmail.com

img:
  prefix:
    client:
      profile: cp
  profile:
    size: 200

jwt:
  secret: HereComesTheSecretToSignThePassword
  expiration: 86400000

aws:
  access_key_id:
  secret_access_key:

s3:
  bucket:
  region: