spring:
  datasource:
    platform: mysql
    url: mysql://b5745f2838c2d9:d4ca17e2@us-cdbr-iron-east-05.cleardb.net/heroku_eb931c3dfc57e59?reconnect=true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  mail:
    host: smtp.gmail.com
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
          ssl:
            enable: true